    mergeMethod: hardreset
    autoMergeHardReset: true
    autoMerge: true
  - base: dev
    upstream: edrivetokenbsc:master
    mergeMethod: hardreset
    autoMergeHardReset: true
    autoMerge: true
  - base: base
    upstream: edrivetokenbsc:master
    mergeMethod: hardreset
    autoMergeHardReset: true
    autoMerge: true
  - base: reverse-proxy
    upstream: edrivetokenbsc:master
    mergeMethod: hardreset
    autoMergeHardReset: true
    autoMerge: true
