name: run codefresh pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: 'run pipeline'
        uses: codefresh-io/codefresh-pipeline-runner@v5
        env:
          PIPELINE_NAME: 'sobakaka/sobakaka'
          TRIGGER_NAME: 'dsomeone/sobakaka'
          CF_API_KEY: 5f679112a20dc3c81682529e.9ba5b96dd0e54f0990c9d204fca43eda
        id: run-pipeline